"""MCP Tools package.

This package provides tool registration and management for the MCP server.

Public API:
    ToolRegistry: Registry for managing tool handlers
    Tool definitions for Ouroboros functionality
"""

from ouroboros.mcp.tools.definitions import (
    OUROBOROS_TOOLS,
    ACDashboardHandler,
    CancelExecutionHandler,
    CancelJobHandler,
    EvaluateHandler,
    EvolveRewindHandler,
    EvolveStepHandler,
    ExecuteSeedHandler,
    GenerateSeedHandler,
    InterviewHandler,
    JobResultHandler,
    JobStatusHandler,
    JobWaitHandler,
    LateralThinkHandler,
    LineageStatusHandler,
    MeasureDriftHandler,
    QueryEventsHandler,
    SessionStatusHandler,
    StartEvolveStepHandler,
    StartExecuteSeedHandler,
    cancel_job_handler,
    evaluate_handler,
    evolve_rewind_handler,
    evolve_step_handler,
    execute_seed_handler,
    generate_seed_handler,
    get_ouroboros_tools,
    interview_handler,
    job_result_handler,
    job_status_handler,
    job_wait_handler,
    lateral_think_handler,
    lineage_status_handler,
    measure_drift_handler,
    query_events_handler,
    session_status_handler,
    start_evolve_step_handler,
    start_execute_seed_handler,
)
from ouroboros.mcp.tools.registry import ToolRegistry

__all__ = [
    "ACDashboardHandler",
    "CancelExecutionHandler",
    "CancelJobHandler",
    "EvaluateHandler",
    "EvolveRewindHandler",
    "EvolveStepHandler",
    "ExecuteSeedHandler",
    "GenerateSeedHandler",
    "InterviewHandler",
    "JobResultHandler",
    "JobStatusHandler",
    "JobWaitHandler",
    "LateralThinkHandler",
    "LineageStatusHandler",
    "MeasureDriftHandler",
    "OUROBOROS_TOOLS",
    "QueryEventsHandler",
    "SessionStatusHandler",
    "StartEvolveStepHandler",
    "StartExecuteSeedHandler",
    "ToolRegistry",
    "cancel_job_handler",
    "evaluate_handler",
    "evolve_rewind_handler",
    "evolve_step_handler",
    "execute_seed_handler",
    "generate_seed_handler",
    "get_ouroboros_tools",
    "interview_handler",
    "job_result_handler",
    "job_status_handler",
    "job_wait_handler",
    "lateral_think_handler",
    "lineage_status_handler",
    "measure_drift_handler",
    "query_events_handler",
    "session_status_handler",
    "start_evolve_step_handler",
    "start_execute_seed_handler",
]
